title: Blog about software development management by Helmut Hoffer von Ankershoffen
baseurl: /
permalink: '/:title/'
layout_style: grid
palette: green
header:
  title: Helmut Hoffer von Ankershoffen
  logo_img: images/logo.png
  has_nav: true
footer:
  content: '&copy; <a rel="me" target="_blank" href="https://helmut.hoffer-von-ankershoffen.me">Helmut Hoffer von Ankershoffen</a> - all rights reserved.'
  links:
    - text: This is me
      url: 'https://helmut.hoffer-von-ankershoffen.me'
      new_window: true
  has_social: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
collections:
  posts:
    permalink: '/posts/:title/'
